### PR TITLE
Follow new compe

### PR DESCRIPTION
**Pull request by hrsh7th**
Sorry. The nvim-compe will apply the breaking change so I'm sending this PR.

https://github.com/hrsh7th/nvim-compe/pull/46

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Why we need to call `unregister_source` here? Can't we just delete the code to not do any initialization?
I'm not 100% sure how will new registering work.

**Comment by hrsh7th** [comment]
Thank you for reviews.
Sorry... It's my easy mistake...

**Comment by kristijanhusak** [comment]
Ok, np. Looks good. When you plan to merge your PR?

**Comment by hrsh7th** [comment]
I will merge it tomorrow (if this PR has no new additional comments or bugreport.)

**Comment by hrsh7th** [comment]
By the way, your nvim-compe integration was exactly what I expected. Thank you very much.

**Comment by kristijanhusak** [comment]
Ok. No additional comments, everything looks ok.
Great. If you want you can add a link to it as an example.

**Comment by hrsh7th** [comment]
hrsh7th/nvim-compe#46 has merged.

**Pull request merged**
